version: '3.8'

services:

  # This is an image based on BirdNET-Analyzer with a couple of patches applied. I hope to be able to replace this
  # with an image they maintain in the future
  birdcage_analyzer:
    restart: unless-stopped
    image: mmcc73/birdnetserver2.4_arm64:latest # If you are running on an arm64 machine, like a Pi 4, 
                                       # use mmcc73/birdnetserver_arm64:latest as the image name
                                       # This will get you 2.3 of the BirdNET model If you want V2.4, use
                                       # mmcc73/birdnetserver2.4:latest or mmcc73/birdnetserver2.4_arm64:latest

  redis:
    image: "redis:latest" #the redis server doesn't need to be exposed outside the virtual network, so no "ports"
                          #mapping is needed
    networks:
      - birdcage_net

  birdcage_backend:
    #image: "mmcc73/birdcage_backend:latest"
    build:
      context: birdcage_backend
      dockerfile: Dockerfile
    ports:
      - "7007:7007"
    environment:
      DATABASE_FILE: /db/birdcage.sqlite3
      API_SERVER_PORT: 7007
      TEMP_DIR_NAME: tmp
      DETECTION_DIR_NAME: detections
      CORS_ORIGINS: '*'
      REDIS_SERVER: redis
      REDIS_PORT: 6379
      CONCURRENCY: 10 # this many processes will get started up to handle concurrent tasks. The app needs (number of streams) + 2?
                      # I think? Maybe +3? Look, I don't really know what I'm doing here.
      JWT_SECRET_KEY: TheseAreTheTimesThatTryMensSouls #this is used to sign tokens, so use your own Enlightenment philosopher quote
      PULSE_SERVER: 172.17.0.1 #If you are using soundcard input, you need an address here that will get you to the host. This is
                               #the default gateway address for docker networks, so in most cases will be fine. If you want
                               #to be fancy you can use a device on a remote machine and put its address here. See the wiki
    tmpfs:
      - /tmp:size=16M #you might want to increase this size if you are recording a bunch of streams, if your
                      # streams are particularly hi-res, or if your analyzer might be periodically unavailable
    volumes:
      - "./detections:/detections"
      - "./db:/db"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - redis
    networks:
      - default
      - birdcage_net

  birdcage_frontend:
    # image: "mmcc73/birdcage_frontend:latest"
    build:
      context: birdcage_frontend
      dockerfile: Dockerfile
    ports:
      - "7008:7008"
    environment:
      API_SERVER_URL: http://10.0.100.226:7007
      WEBUI_PORT: 7008
      #TITLE_TEXT: Your Title Here
      #TITLE_LINK: http://yourlinkhere
      #Include the above variables if you want to put some text, and optionally a link, in the nav bar
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    networks:
      - birdcage_net

networks:
  birdcage_net:
    driver: bridge
